# Generated by Django 5.2.10 on 2026-03-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("address", models.TextField(blank=True, verbose_name="Адрес доставки")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("file", models.FileField(blank=True, null=True, upload_to="orders/files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=255, verbose_name="Товар")),
                ("option_size", models.CharField(max_length=50, verbose_name="Размер")),
                ("product_sku", models.CharField(blank=True, max_length=100, verbose_name="Артикул")),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="order.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заявке",
                "verbose_name_plural": "Товары в заявке",
            },
        ),
    ]
