# Generated by Django 5.2.10 on 2026-03-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_tg_chat_id_orderitem_tg_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tg_chat_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="tg_chat_id",
        ),
    ]
