# Generated by Django 5.2.10 on 2026-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_tg_chat_id_remove_orderitem_tg_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="unit",
            field=models.CharField(default="шт", max_length=150, verbose_name="Единица измерения"),
        ),
    ]
