server {
    listen 80;

    location /admin/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
    }

    location /static/ {
    alias /project/src/static/;
    }

    location /media/ {
        alias /project/src/media/;
    }

    location / {
        proxy_pass http://frontend:3000/;
    }
}