# Generated by Django 5.2.10 on 2026-03-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_deliverypage_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaticPageSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="pages.staticpage"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StaticPageItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="pages.staticpagesection"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
