# Generated by Django 5.2.10 on 2026-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_staticpage_staticpagesection_staticpageitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
