# Generated by Django 5.2.10 on 2026-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_staticpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryitem",
            name="title",
            field=models.CharField(default="Без заголока", max_length=255),
            preserve_default=False,
        ),
    ]
