# Generated by Django 5.2.10 on 2026-04-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_deliveryitem_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", models.CharField(default="#F2F3F4", max_length=7)),
                ("text", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="pages.staticpage"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
