# Generated by Django 5.2.10 on 2026-04-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_deliveryzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryzone",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="pages.deliverypage"
            ),
        ),
    ]
