# Generated by Django 5.2.10 on 2026-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Телеграм chat_id"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Телеграм chat_id"),
        ),
    ]
