# Generated by Django 5.2.10 on 2026-03-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Категория товара")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/categories/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название товара")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("sku", models.CharField(max_length=150, unique=True, verbose_name="Артикул")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание товара")),
                ("unit", models.CharField(max_length=150, verbose_name="Единица измерения")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/products/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена"),
                ),
                ("sku", models.CharField(max_length=150, unique=True, verbose_name="Артикул")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер товара",
                "verbose_name_plural": "Размеры товара",
            },
        ),
    ]
