# Generated by Django 5.2.10 on 2026-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoption",
            name="price",
        ),
    ]
