# Generated by Django 5.2.10 on 2026-03-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productoption_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="size",
            field=models.CharField(max_length=150, verbose_name="Размер"),
        ),
    ]
