# Generated by Django 5.2.10 on 2026-03-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_slug_alter_productoption_size"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together={("product", "size")},
        ),
    ]
