# Generated by Django 5.2.10 on 2026-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productoption_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="unit",
            field=models.CharField(default="шт", max_length=150, verbose_name="Единица измерения"),
        ),
    ]
