# Generated by Django 5.2.10 on 2026-04-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productoption_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="color_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/products/options/"),
        ),
    ]
