# Generated by Django 5.2.10 on 2026-04-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productoption_color_productoption_color_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="productoption",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productoption",
            name="color_name",
        ),
        migrations.RemoveField(
            model_name="productoption",
            name="image",
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color_name", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="colors", to="products.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "color_name")},
            },
        ),
    ]
