name: Django CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: testsecret
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      DB_HOST: localhost
      DB_PORT: 5432
      DEBUG: "True"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - run: poetry run python backend/manage.py migrate
      - run: poetry run python backend/manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vostkrep:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vostkrep:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_KEY }}" > key
          chmod 600 key

          ssh -i key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            docker compose pull
            docker compose up -d
          EOF

